#!/usr/bin/env python3
"""Generate Adafruit-GFX font headers from Roboto TTFs for the ESP32 UI.

The classic UI font is the 6x8 bitmap font scaled by N (cap height 7*N px).
For each classic size we emit a Roboto GFXfont whose cap height matches, so
the smooth font drops into the same layout coordinates.

Usage:
    python tools/gen_fonts.py <Roboto-Regular.ttf> <Roboto-Bold.ttf>

Writes esp32/src/fonts/roboto_s{2,3,4,5}.h. Roboto is Apache-2.0 licensed
(commercial use fine, attribution in the generated headers).
"""

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "esp32" / "src" / "fonts"

FIRST, LAST = 32, 126

# (classic size, cap height px, ttf index: 0=regular 1=bold)
SIZES = [(2, 14, 0), (3, 21, 1), (4, 28, 1), (5, 35, 1)]


def cap_height(font: ImageFont.FreeTypeFont) -> int:
    bbox = font.getbbox("A")
    return bbox[3] - bbox[1]


def pick_px(ttf: str, target_cap: int) -> ImageFont.FreeTypeFont:
    best, best_err = None, 10**9
    for px in range(target_cap, target_cap * 2 + 1):
        f = ImageFont.truetype(ttf, px)
        err = abs(cap_height(f) - target_cap)
        if err < best_err:
            best, best_err = f, err
        if err == 0:
            break
    return best


def render_glyph(font: ImageFont.FreeTypeFont, ch: str):
    """Returns (bits, w, h, xAdvance, xOffset, yOffset) - offsets per GFXfont."""
    ascent, _ = font.getmetrics()
    pad = font.size
    img = Image.new("L", (pad * 4, pad * 4), 0)
    d = ImageDraw.Draw(img)
    d.fontmode = "1"  # FreeType mono hinting - crisp 1-bit output
    d.text((pad, pad), ch, font=font, fill=255)
    bbox = img.getbbox()
    adv = int(round(font.getlength(ch)))
    if bbox is None:
        return [], 0, 0, adv, 0, 0
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    px = img.load()
    bits = [1 if px[x0 + xx, y0 + yy] >= 128 else 0 for yy in range(h) for xx in range(w)]
    return bits, w, h, adv, x0 - pad, y0 - (pad + ascent)


def emit(font: ImageFont.FreeTypeFont, name: str, path: Path, ttf_name: str) -> None:
    bitmap: list[int] = []
    glyphs = []
    for code in range(FIRST, LAST + 1):
        bits, w, h, adv, xo, yo = render_glyph(font, chr(code))
        offset = len(bitmap)
        acc, nbits = 0, 0
        for b in bits:
            acc = (acc << 1) | b
            nbits += 1
            if nbits == 8:
                bitmap.append(acc)
                acc, nbits = 0, 0
        if nbits:
            bitmap.append(acc << (8 - nbits))
        glyphs.append((offset, w, h, adv, xo, yo, chr(code)))

    ascent, descent = font.getmetrics()
    y_advance = ascent + descent
    lines = [
        f"// Generated by tools/gen_fonts.py from {ttf_name} at {font.size}px",
        f"// (cap height {cap_height(font)}px). Roboto: Copyright 2011 Google Inc.,",
        "// licensed under the Apache License, Version 2.0.",
        "#pragma once",
        "#include <Arduino.h> // GFXfont comes from Arduino_GFX, include this after it",
        "",
        f"static const uint8_t {name}Bitmaps[] PROGMEM = {{",
    ]
    for i in range(0, len(bitmap), 12):
        chunk = ", ".join(f"0x{b:02X}" for b in bitmap[i : i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    lines.append(f"static const GFXglyph {name}Glyphs[] PROGMEM = {{")
    for offset, w, h, adv, xo, yo, ch in glyphs:
        safe = ch if ch not in ("\\", "'") else "\\" + ch
        lines.append(
            f"    {{{offset}, {w}, {h}, {adv}, {xo}, {yo}}}, // '{safe}'"
        )
    lines.append("};")
    lines.append("")
    lines.append(
        f"static const GFXfont {name} PROGMEM = {{(uint8_t *){name}Bitmaps, "
        f"(GFXglyph *){name}Glyphs, {FIRST}, {LAST}, {y_advance}}};"
    )
    lines.append("")
    path.write_text("\n".join(lines), encoding="ascii")
    print(f"{path.name}: {font.size}px, {len(bitmap)} bitmap bytes")


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    ttfs = [sys.argv[1], sys.argv[2]]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for classic, cap, weight in SIZES:
        font = pick_px(ttfs[weight], cap)
        emit(font, f"RobotoS{classic}", OUT_DIR / f"roboto_s{classic}.h",
             Path(ttfs[weight]).name)


if __name__ == "__main__":
    main()
